server:
  port: 8888
spring:
  application:
    name: Alipay
  datasource:
    url: 192.168.216.18:3306
    data-username: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
alipay:
  # 支付宝网关名、partnerId和appId
  openApiDomain: https://openapi.alipay.com/gateway.do
  mcloudApiDomain: http://mcloudmonitor.com/gateway.do
  appId: 9021000144671717
  pid: 2088721059035992
  # RSA私钥、公钥和支付宝公钥
  #此处请填写你的应用私钥且转PKCS8格式
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfNrLfv9cIOnYkpfIkaQcQXmCdsWbznqvdhgEe20fsf7PSs6XonP9fX7DXg8ZGYZ7F5f7XeUGEe/4+qLP29ygq+wvByaUNnzb32r8wRdiYS8lxy3Y5FPzB1qmQUvgpIdYyIRbuuhSprC32UxYTZKF51qn31Qfth9AiGbYw0ToRrG++71ODkpOjFlh2VCAMC67hclLyuWGaA4Nte156rIX62FZnQz0uocazyqdHZHA1diAgEzWFD5FJ9s++0GRbxiZjeJfdSXjojOebB5OTGTCfrN/AWziPURP3VWVA7JlLhfiplCHLHyUVs9F+yobZWBeeSfq08CZiyE3O96SCiwrtAgMBAAECggEAb9fm9BM5pUgcMkZ4wWceVTtXN6+lmMIADY/TPa/g6JwU4JDenXecVY1NFzg0ksCE3pRg31EI216XDcFJGtYo23ibm7hhQB52aMq7v9dw/htPGadKF3NM04ZOe1othgeFBpYEHBOP7FlNuFpJiboJTSOlJrn55bygUzQorkZsOnj9bcfaWEF1H0rcUSHkUgovuSCo7t7peFgZNij0CV7vDP3dZTvt7qzea7v9O7or2NyLLnVXNP4fbgtTL7pjySdGs3YNkO32S3T4+rjboqXN9arrlutF3itOrvDs7ZzJYt2txwZuHlUDlNP/kaZccYfCLfFRfSOsebVzuLgXcXuDaQKBgQDySyZ5eOkoUyx7IVMJ+emLPH2cE+e18+Tix4TrzqxQaKlhW5ZwJ486KncaBFafWjtG7ZLzm7Cy8i50XLmU4Ic6Yy8RW5jxm/MQl25q+9UemBtQyPb8MHgoBszpauDTBZkuKgnwdYnY4vc1oBNZ5u6rXAm2ucMieTuNXiRmCit24wKBgQCoOGavC9pVehuOdc+OIt42Q+Bcs7ESfcB9F5wb5BdLbLjTPfU6IoPm2UZVmgaC9RiBenmNn4pT+K4/oToOcPxwm1XgGuMq+U6OyIMR3J8BZ/78C2H8Jf0u6+XTOVDaqQrv5/pxuNs0z6M9NTeMMJygcPw9c0/tUT6mfnBJSE1P7wKBgDl0srH5hyjF2HV2aI+kEMqw1ISPf9H4/Rz9/TpB70C+IPRyWJFOADvl2Ap2Xug46HegXMmh8NvubC+x0VxJhifFX2L5WqJovdIAZvG9uEMiBNA6Z79T6xpqymrLqnbADBwTYfoAlWi2IbM4u34FMjG2iKMpF+nz37hdS7pazQXLAoGAJTILamsphLryOubL1PbawY7ynizRW3BYzpAY4YXmrLPGjlbl0UvudG3YgncDN5OwLnkBRZJgSL708Hba2nSbLN779wia8Fadyy6E5L8unWX8WIi/yrwvpl9cuv6yZRb5pyBZHSotthivVIpe1O2uxD8XVxMXOjc7rh7I/zswdRsCgYEA0dGQMQ0/PhAqJ0JEsMzAqjP2ndH3UfvbAgkrvGDAX/sA/k52HxAGgVsioNGauyKLcL3nGNq6ghsaawp/HGfa03eQMJGCf46dEEULDT8pdOfuJRaCwI5eruQg3/vBPSOwXf49d+MMyI/Y61z3EvMeesm3EdgBAMN+3Ni90vU8SVA=
  #此处请填写你的应用公钥
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzay37/XCDp2JKXyJGkHEF5gnbFm856r3YYBHttH7H+z0rOl6Jz/X1+w14PGRmGexeX+13lBhHv+Pqiz9vcoKvsLwcmlDZ8299q/MEXYmEvJcct2ORT8wdapkFL4KSHWMiEW7roUqawt9lMWE2Shedap99UH7YfQIhm2MNE6Eaxvvu9Tg5KToxZYdlQgDAuu4XJS8rlhmgODbXteeqyF+thWZ0M9LqHGs8qnR2RwNXYgIBM1hQ+RSfbPvtBkW8YmY3iX3Ul46IznmweTkxkwn6zfwFs4j1ET91VlQOyZS4X4qZQhyx8lFbPRfsqG2VgXnkn6tPAmYshNzvekgosK7QIDAQAB
  #SHA256withRsa对应支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlRT92ZnGN8o4REvf0Bed9TQWhJr4ElKfUbe6MYWWOkVhKi+iXh3hkyicY9+4V4jUbuZuS7LOcFYa5IrPTjB3f0kkqwiLI4QM+AuUrf4ZJ3Du5cGs1qqWMUEsYhtn5g8USldZz0o35MGikOGKAllQusvBhKkUojsVb/pkTxYoAhkycrjuLmP2G3g622YABVJIUoS8CE3JGOz9nlW9wjBhH8pTqEWG3eaG6zp4+H2tJA+jewA0mMKOewNtfVHh0qJW3XI0NviP5V5jZAgCbB5J0xWyuZa2YoVPUv/9QUraQdIHvgIFG0rygeegK1eDJIBsvvlWufr8Mp1v/ppi+/Ea2QIDAQAB
  # 签名类型: RSA->SHA1withRsa,RSA2->SHA256withRsa
  signType: RSA2
  #异步通知url(注意拦截器是否拦截)
  notifyUrl: http://loving-rationally-lacewing.ngrok-free.app/alipay/ZFBcallbackAction.do
# application.properties

